image: Visual Studio 2017

before_build:
  - nuget restore Telegram.Bot.Framework.sln

configuration:
 - Debug;TargetFramework=net45
 - Release;TargetFramework=net45

build:
  project: Telegram.Bot.Framework.Net45.sln
  publish_nuget: true

test:
  assemblies:
    only:
      - '**Tests.Net45.dll'

nuget:
  disable_publish_on_pr: true

# deploy:
#   - provider: NuGet
#     artifact: /.*Telegram.Bot.Framework.*\.nupkg/
#     api_key:
#       secure: HHTe2/56sywbQ4uGD1fOeOBWjggVknMVXKhBu7978+LPJQCLJ28Ji9suN7nIfSGY
#     on:
#       branch: master


for:
-
  branches:
    only:
      - master
      - develop
  build:
    project: src\Telegram.Bot.Framework\Telegram.Bot.Framework.csproj
    publish_nuget: true
  configuration: Release
