image: Visual Studio 2017

nuget:
  disable_publish_on_pr: true

before_build:
  - nuget restore Telegram.Bot.Framework.sln

configuration:
  - Debug
  - Release

build:
  project: Telegram.Bot.Framework.sln
  publish_nuget: true

deploy:
  - provider: NuGet
    artifact: /.*Telegram.Bot.Framework.*\.nupkg/
    api_key:
      secure: YkjOSiZBBd9G7DhOajlWTzmLAcx6ojYoIcyMjpC8DQHklWXLCzN4rfxnvgDFsZ7O
    on:
      branch: /^r\/.+/
      configuration: Release


for:
- # when releasing from master branch, build the package only
  branches:
    only:
      - /^r\/.+/
  configuration: Release
  test: off
