image: Visual Studio 2017

before_build:
  - nuget restore Telegram.Bot.Framework.sln

configuration:
 - Debug
 - Release

environment:
  matrix:
    - target_framework: net45
    - target_framework: net471

build:
  project: Telegram.Bot.Framework.sln
  publish_nuget: true

test:
  assemblies:
# run unit tests only in a Windows environment
    only:
      - '**\UnitTests.dll'

nuget:
  disable_publish_on_pr: true

# deploy:
#   - provider: NuGet
#     artifact: /.*Telegram.Bot.Framework.*\.nupkg/
#     api_key:
#       secure: HHTe2/56sywbQ4uGD1fOeOBWjggVknMVXKhBu7978+LPJQCLJ28Ji9suN7nIfSGY
#     on:
#       branch: master


for:
-
  branches:
    only:
      - master
      - develop
  configuration: Release
