image: Visual Studio 2017

nuget:
  disable_publish_on_pr: true

before_build:
  - nuget restore Telegram.Bot.Framework.sln

configuration:
  - Debug
  - Release

build:
  project: Telegram.Bot.Framework.sln
  publish_nuget: true

test:
  assemblies:
    only:
      - '**\*Tests*.dll'

# deploy:
#   - provider: NuGet
#     artifact: /.*Telegram.Bot.Framework.*\.nupkg/
#     api_key:
#       secure: HHTe2/56sywbQ4uGD1fOeOBWjggVknMVXKhBu7978+LPJQCLJ28Ji9suN7nIfSGY
#     on:
#       branch: master


for:
- # when releasing from master branch, build the package only
  branches:
    only:
      - master
  configuration: Release
  test: off
