image: Visual Studio 2017

nuget:
  disable_publish_on_pr: true

before_build:
  - nuget restore Telegram.Bot.Framework.sln

configuration:
  - Debug
  - Release

build:
  project: Telegram.Bot.Framework.sln

test: off

# deploy:
#   - provider: NuGet
#     artifact: /.*Telegram.Bot.Framework.*\.nupkg/
#     api_key:
#       secure: HHTe2/56sywbQ4uGD1fOeOBWjggVknMVXKhBu7978+LPJQCLJ28Ji9suN7nIfSGY
#     on:
#       branch: master


for:


- # Full .NET Framework projects only
  build:
    project: Telegram.Bot.Framework.Net45.sln
    publish_nuget: true
  test:
  assemblies:
    only:
      - '**Tests.Net45.dll'


- # .NET Core projects only
  build:
    project: Telegram.Bot.Framework.NetCore.sln
    publish_nuget: true
  test:
  assemblies:
    only:
      - '**Tests.NetCore.dll'


- # Build the package only for releases
  branches:
    only:
      - master
  build:
    project: src\Telegram.Bot.Framework\Telegram.Bot.Framework.csproj
    publish_nuget: true
  configuration: Release
