dist: trusty
sudo: required
language: node_js
node_js:
  - node
notifications:
  email: false
services:
  - docker

install:
  - cd scripts && npm install && cd ..

script:
  - node scripts/build 
  # - node scripts/test

deploy:
  - provider: script
    skip_cleanup: true
    script: node scripts/deploy Production
    on:
      branch: v2


# Disable "Build pushed pull requests"


# env:
#   DEPLOY_SETTINGS_JSON: A mapping of environment to the deployment types and their options.
#   {
#     "Production": [
#       { "type": "heroku", 
#         "options": { 
#           "app": "foo-staging", "source": "foo:latest", "dyno": "web", "user": "foo@example.org", "token": "TOKEN" 
#         }
#       }
#     ]
#   }
#####
# export DEPLOY_SETTINGS_JSON='{"Production":[{"type":"heroku","options": {"app": "sample-tgbot","source":"quickstart:latest","dyno":"web","user":"foo@example.org","token":"TOKEN"}}]}'