version: '2'

services:

  nginx:
    container_name: nginx
    build:
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
      - "8443:8443"
    links:
      - sample-echo-bot
      - sample-games-bot
    networks:
      - bots-network

  sample-echo-bot:
    container_name: sample-echo-bot
    build:
      context: ../sample/SampleEchoBot
      args:
        project: SampleEchoBot
    expose:
      - "80"
    networks:
      - bots-network

  sample-games-bot:
    container_name: sample-games-bot
    build:
      context: ../sample/SampleGames
      args:
        project: SampleGames
    expose:
      - "80"
    networks:
      - bots-network

networks: 
  bots-network:
    driver: bridge
